### PR TITLE
Adding Classes and Functions to pull Sec Data

### PR DESCRIPTION
**Pull request by itwela**
I decided to get started on the Sec Data pulling. As of now  you can input a stock ticker like Appl or Tsla and it will return every '10-q'  filling related to that stock symbol.

### What is a 10-q form? 
SEC Form 10-Q is a comprehensive report of financial performance that must be submitted quarterly by all public companies to the Securities and Exchange Commission (SEC). In the 10-Q, firms are required to disclose relevant information regarding their finances related to their business operations.

This is just a start if you guys like this Ill start really building out more functions to pull different kinds of data. Also let me know what data would even make sense to pull? Its a lot of options and I'm sure you all have some great ideas as well!

### CODE REVIEW

**Comment by blue-codes-yep** [comment]
Just looking at the requirements.txt, I think this going to break some people's app, 

`beautifulsoup4 @ file:///C:/b/abs_0agyz1wsr4/croot/beautifulsoup4-split_1681493048687/work `

For example I don't even have a C drive. Also would move your API key into a .env, and share it personally between the contributors if needed. 

Going to wait on approving this and see what some the other folks think @Carsoncantcode, what do you think about doing this for the SEC data? 

-- Side note: I did the same thing multiple times but when you merge over, merge to main from your branch. Not forked main to main. It would be forked branch to main branch on the main repo.

**Comment by itwela** [comment]
So iImade the changes of protecting the env file and removed the breaking python modules added by conda. This should make it so that anybody can use it.

You can get an api key from here (its free) :
|-----  https://sec-api.io

**Comment by blue-codes-yep** [comment]
The requirements is including all of your libraries you have on your machine. 

Surely pygame isn't being used in the code you sent haha. 

Going from 38 requirements to like 200.
( May be easier to re-fork, branch, add your code, and then merge )

**Comment by itwela** [comment]
Thank you for pointing that out I see now the error in my ways. I copied the old requiremtnts.txt file and just added sec-api to it because I only added 1 library and conda added all of my modules on my laptop. 

I'm off of using conda for this project at least just going run with pip for now.

**Review by blue-codes-yep — APPROVED** [review]

**Pull request merged**
